# Generated by Django 5.0.6 on 2024-06-26 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azbankgateways', '0005_alter_bank_bank_type_alter_bank_created_at_and_more'),
        ('payments', '0002_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت ها'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azbankgateways.bank', verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.package', verbose_name='بسته'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
