# Generated by Django 5.0.6 on 2024-06-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_alter_payment_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='price',
            new_name='amount',
        ),
    ]
