# Generated by Django 5.0.6 on 2024-06-26 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_price_payment_amount'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'بسته', 'verbose_name_plural': 'بسته ها'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراک', 'verbose_name_plural': 'اشتراک ها'},
        ),
        migrations.AddField(
            model_name='package',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات انگلیسی'),
        ),
        migrations.AddField(
            model_name='package',
            name='title_en',
            field=models.CharField(default='default', max_length=200, verbose_name='عنوان انگلیسی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات فارسی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت بسته'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان فارسی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.package', verbose_name='بسته'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.payment', verbose_name='پرداخت'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
